### PR TITLE
Consider attributes modification in toString

### PR DESCRIPTION
**Pull request by Sharcoux**
I thought we could take into account the attributes modifications with something like this.

What do you think?

### CODE REVIEW

**Comment by taoqf** [comment]
Em, Will this slow down us?
Could you pls add some tests for this?

**Comment by Sharcoux** [comment]
Converting the attributes object back into a string might take a small amount of time more than using the raw string. But this is only the case if the _attrs property has been created. But we might improve the speed if we only do this step if a change has occured.

To do that, we must notice that there are some issues in the current lib and they should probably be taken care of first of all.

There are 3 properties containing the attributes: `_attrs`, `_rawAttrs` and `rawAttrs`. The issue is that editing one of these properties doesn't affect the others, and only the changes made to rawAttrs are taken into account when stringifying.

We should probably first think about a way to make sure that all 3 properties remain in sync at all times, don't you think?

I can see multiple ways of doing so:

1. Create a `setAttribute` method that would be the only way of changing, creating or removing an attribute value.
2. Detect any modification to any of the 3 properties, maybe using a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), and then updating the other 2 accordingly.
3. Merging the 3 properties data each time we need to access any of them
4. Keep only one of the 3 property, and each time we request another one, we actually convert the current one into the other and delete the original.

What do you prefer? Personally I would go with 1 or 4.

**Comment by taoqf** [comment]
1 seems  good to me.
I just worried about this library getting more and more heavier some day.
But we must look forward, if it just take little price to work better, I am glad to see.

**Comment by Sharcoux** [comment]
Yes. This was just a draft to discuss the best way to make the changes. I'll make a full PR from what we discussed.
If we don't add external library and if the things we add don't add significative performance changes, I don't believe people would mind if the lib takes a few more kB of plain code.

**Comment by Sharcoux** [comment]
On my side, I think it's all good. Tell me if I missed something.

**Pull request merged**
