### PR TITLE
Fix Issue #51 and #136

### PR DESCRIPTION
**Pull request by the-self-taught-programmer**
- Update `kMarkupPattern` regex pattern to include `html tags` and `vuejs` attributes.
- Add `136.js` unit test
- Update `51.js` unit test
- Add prettierrc

### CODE REVIEW

**Comment by nonara** [comment]
Have you checked to see performance impact? Positive lookahead in regex tends to be expensive. Curious to know what the difference is here

**Comment by the-self-taught-programmer** [comment]
Do we have some performance tests that I can use?

**Comment by nonara** [comment]
There's a benchmark tool in the tests dir. It uses the built version, so you'll want to build dist first.

**Comment by taoqf** [comment]
Thank you.

**Pull request merged**
